"use client";

import React, { useState } from "react";
import { Copy } from "lucide-react";
import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { useToast } from "@/components/ui/Toast";
import { copyToClipboard } from "@/lib/utils";

export function RobotsGeneratorTool() {
  const [defaultAccess, setDefaultAccess] = useState<"allow" | "disallow">("allow");
  const [sitemapUrl, setSitemapUrl] = useState<string>("https://omnicraft.dev/sitemap.xml");
  const [disallowedPaths, setDisallowedPaths] = useState<string>("/admin/\n/api/\n/private/");
  const { success } = useToast();

  const paths = disallowedPaths.split("\n").map((p) => p.trim()).filter(Boolean);
  const generatedRobots = `# robots.txt generated by OmniCraft
User-agent: *
${defaultAccess === "disallow" ? "Disallow: /" : "Allow: /"}
${paths.map((p) => `Disallow: ${p}`).join("\n")}

Sitemap: ${sitemapUrl}`;

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div>
            <label className="text-xs font-bold text-slate-700 dark:text-slate-200 mb-1.5 block">
              Default Search Engine Crawler Access
            </label>
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => setDefaultAccess("allow")}
                className={`p-3 rounded-2xl border text-xs font-bold transition-all cursor-pointer ${defaultAccess === "allow" ? "bg-indigo-600 border-indigo-500 text-white shadow-xs" : "bg-slate-100 dark:bg-[#0f172a] border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"}`}
              >
                Allow All
              </button>
              <button
                onClick={() => setDefaultAccess("disallow")}
                className={`p-3 rounded-2xl border text-xs font-bold transition-all cursor-pointer ${defaultAccess === "disallow" ? "bg-indigo-600 border-indigo-500 text-white shadow-xs" : "bg-slate-100 dark:bg-[#0f172a] border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"}`}
              >
                Disallow All
              </button>
            </div>
          </div>

          <Input label="XML Sitemap URL" value={sitemapUrl} onChange={(e) => setSitemapUrl(e.target.value)} />

          <div>
            <label className="text-xs font-bold text-slate-700 dark:text-slate-200 mb-1.5 block">
              Restricted / Disallowed Directories (1 per line)
            </label>
            <textarea
              value={disallowedPaths}
              onChange={(e) => setDisallowedPaths(e.target.value)}
              rows={4}
              className="w-full p-4 rounded-2xl border border-slate-200 dark:border-white/10 bg-white/90 dark:bg-[#090e1c] text-slate-900 dark:text-white text-xs font-mono focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 shadow-xs dark:shadow-inner"
            />
          </div>
        </div>

        <div className="space-y-2">
          <label className="text-xs font-bold text-slate-700 dark:text-slate-200 block">
            Generated robots.txt Preview
          </label>
          <textarea
            readOnly
            value={generatedRobots}
            rows={10}
            className="w-full p-4 rounded-2xl border border-slate-200 dark:border-white/10 bg-slate-100 dark:bg-[#060a14] text-emerald-600 dark:text-emerald-400 font-mono text-xs shadow-inner"
          />
          <div className="flex justify-end">
            <Button
              variant="outline"
              size="md"
              onClick={async () => {
                const ok = await copyToClipboard(generatedRobots);
                if (ok) success("robots.txt copied to clipboard");
              }}
              leftIcon={<Copy className="w-4 h-4" />}
            >
              Copy robots.txt
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

