import { CategoryDefinition, ToolCategoryId } from "./types";

export const TOOL_CATEGORIES: Record<ToolCategoryId, CategoryDefinition> = {
  pdf: {
    id: "pdf",
    name: "PDF Tools",
    slug: "pdf",
    description: "Merge, split, compress, rotate, watermark, protect, and convert PDF documents in your browser.",
    icon: "FileText",
    colorGradient: "from-rose-500 to-red-600",
    accentColor: "#f43f5e",
    sortOrder: 1,
  },
  image: {
    id: "image",
    name: "Image Tools",
    slug: "image",
    description: "Compress, resize, crop, convert JPG/PNG/WEBP, remove backgrounds, generate memes and color palettes.",
    icon: "Image",
    colorGradient: "from-purple-500 to-indigo-600",
    accentColor: "#a855f7",
    sortOrder: 2,
  },
  "qr-barcode": {
    id: "qr-barcode",
    name: "QR & Barcode",
    slug: "qr-barcode",
    description: "Generate and scan customized QR codes with logos, WiFi credentials, vCards, and industrial barcodes.",
    icon: "QrCode",
    colorGradient: "from-blue-500 to-cyan-600",
    accentColor: "#3b82f6",
    sortOrder: 3,
  },
  converters: {
    id: "converters",
    name: "Unit & Currency",
    slug: "converters",
    description: "Instant unit converters for length, weight, speed, temperature, data storage, and live real-time currency rates.",
    icon: "ArrowLeftRight",
    colorGradient: "from-emerald-500 to-teal-600",
    accentColor: "#10b981",
    sortOrder: 4,
  },
  calculators: {
    id: "calculators",
    name: "Calculators",
    slug: "calculators",
    description: "Scientific, financial, EMI loans, compound interest, tax/GST, BMI, age, and date difference calculators.",
    icon: "Calculator",
    colorGradient: "from-amber-500 to-orange-600",
    accentColor: "#f59e0b",
    sortOrder: 5,
  },
  text: {
    id: "text",
    name: "Text Utilities",
    slug: "text",
    description: "Word & character counter, case converter, remove duplicate lines, text diff comparison, and string cleaners.",
    icon: "Type",
    colorGradient: "from-indigo-500 to-violet-600",
    accentColor: "#6366f1",
    sortOrder: 6,
  },
  developer: {
    id: "developer",
    name: "Developer Tools",
    slug: "developer",
    description: "JSON formatter/validator, XML/HTML/SQL formatters, Base64, UUID generator, JWT decoder, and regex tester.",
    icon: "Code2",
    colorGradient: "from-cyan-500 to-blue-600",
    accentColor: "#06b6d4",
    sortOrder: 7,
  },
  seo: {
    id: "seo",
    name: "SEO & Webmaster",
    slug: "seo",
    description: "Meta tag generator, Open Graph simulator, robots.txt & sitemap generator, keyword density checker.",
    icon: "Search",
    colorGradient: "from-lime-500 to-emerald-600",
    accentColor: "#84cc16",
    sortOrder: 8,
  },
  ai: {
    id: "ai",
    name: "AI & Writing",
    slug: "ai",
    description: "AI-powered text summarizer, grammar enhancer, paraphraser, email generator, and prompt optimizer.",
    icon: "Sparkles",
    colorGradient: "from-pink-500 to-rose-600",
    accentColor: "#ec4899",
    sortOrder: 9,
  },
  video: {
    id: "video",
    name: "Video Tools",
    slug: "video",
    description: "Video metadata inspector, video muter, speed controller, aspect ratio calculator, and GIF frame extractor.",
    icon: "Video",
    colorGradient: "from-red-500 to-amber-600",
    accentColor: "#ef4444",
    sortOrder: 10,
  },
  audio: {
    id: "audio",
    name: "Audio Tools",
    slug: "audio",
    description: "Audio trimmer, playback rate changer, volume booster, and waveform inspector.",
    icon: "Music",
    colorGradient: "from-fuchsia-500 to-pink-600",
    accentColor: "#d946ef",
    sortOrder: 11,
  },
  office: {
    id: "office",
    name: "Office & Data",
    slug: "office",
    description: "CSV to JSON converter, JSON to CSV exporter, Excel table viewer, and delimiter parser.",
    icon: "Sheet",
    colorGradient: "from-teal-500 to-cyan-600",
    accentColor: "#14b8a6",
    sortOrder: 12,
  },
  security: {
    id: "security",
    name: "Security & Privacy",
    slug: "security",
    description: "Strong password generator, password strength evaluator, MD5/SHA-256 hash generator, and random secrets.",
    icon: "ShieldCheck",
    colorGradient: "from-slate-700 to-slate-900",
    accentColor: "#475569",
    sortOrder: 13,
  },
  web: {
    id: "web",
    name: "Web Utilities",
    slug: "web",
    description: "URL encoder/decoder, User-Agent inspector, HTTP status code directory, and timestamp converters.",
    icon: "Globe",
    colorGradient: "from-sky-500 to-indigo-600",
    accentColor: "#0ea5e9",
    sortOrder: 14,
  },
  social: {
    id: "social",
    name: "Social Media",
    slug: "social",
    description: "Trending hashtag generator, social bio creator, aspect ratio resize helper for YouTube/Instagram/X.",
    icon: "Share2",
    colorGradient: "from-rose-500 to-orange-500",
    accentColor: "#f43f5e",
    sortOrder: 15,
  },
  design: {
    id: "design",
    name: "Design & CSS",
    slug: "design",
    description: "Color palette generator, CSS box shadow designer, CSS gradient builder, and glassmorphism generator.",
    icon: "Palette",
    colorGradient: "from-violet-500 to-purple-600",
    accentColor: "#8b5cf6",
    sortOrder: 16,
  },
  productivity: {
    id: "productivity",
    name: "Productivity",
    slug: "productivity",
    description: "Pomodoro focus timer, stopwatch, decision random picker, checklist creator, and habit tracker.",
    icon: "Clock",
    colorGradient: "from-amber-500 to-yellow-600",
    accentColor: "#eab308",
    sortOrder: 17,
  },
};

export const CATEGORY_LIST = Object.values(TOOL_CATEGORIES).sort((a, b) => a.sortOrder - b.sortOrder);
